<?php
/**
 * @file
 * Code for the StickySlot module.
 */

/**
 * Implements hook_page_alter().
 */
function stickyslot_page_alter(&$page) {
  $page['content']['#attached']['js'][] = libraries_get_path('sticky-kit') . '/jquery.sticky-kit.js';
  $page['content']['#attached']['js'][] = drupal_get_path('module', 'stickyslot') . '/js/stickyslot_sticky.js'; 
}

/**
 * Implements hook_page_build().
 */
function stickyslot_page_build() {
  if ($plugin = context_get_plugin('reaction', 'stickyslot')) {
    $plugin->execute();
  }
}

/**
 * Implements hook_context_registry().
 */
function stickyslot_context_registry() {
  return [
    'reactions' => [
      'stickyslot' => [
        'title' => t('Sticky Slot'),
        'plugin' => 'stickyslot_context_reaction',
      ],
    ],
  ];
}

/**
 * Implements hook_context_plugins().
 */
function stickyslot_context_plugins() {
  $plugins['stickyslot_context_reaction'] = [
    'handler' => [
      'path' => drupal_get_path('module', 'stickyslot') . '/plugins',
      'file' => 'stickyslot_context_reaction.inc',
      'class' => 'StickySlotContextReaction',
      'parent' => 'context_condition',
    ],
  ];
  return $plugins;
}
